### ISSUE TITLE
version

### ISSUE THREAD

**Issue by cngeru** [paulxuca/shirts#1]
Does a new version exist?

**Comment by paulxuca** [comment]
Hi there! 👋

Unfortunately not. There are no plans to continue this project or maintain it. If you need any help with running it, I’d be glad to help!

**Comment by cngeru** [comment]
Do you have a version with just the frontend react and probably not using redux?

**Comment by paulxuca** [comment]
Hi!

No sorry, I unfortunately do not. If you wanted to do that and run into any issues, I'd be glad to help :)

**Comment by zayn-m** [comment]
Hi, 
I'm getting this error while npm install: 
Failed at the ngrok@2.2.2 postinstall script. This is probably not a problem with npm. There is likely additional logging output above.

**Comment by paulxuca** [comment]
Hi @Zayn484 👋 Can you post the full error log? I'm not actively working on this project anymore but can help you get it running locally!

**Comment by danlim26** [comment]
Hi @paulxuca - I'm new to react and nodejs, can you help me run your project? I tried npm install and i get this error: 

5667 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/readline2: Integrity verification failed for sha512-PIvOLYLW/0/xBSe5U3zKY9bF/fHkavisDBsByOY/7sCTC2orJWjQ9J/varBTRVvog34B5G7za26mBn0ZggI5vw== (C:\Users\V002322\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\3c\8b\ce2d82d6ff4ff10527b9537cca63d6c5fdf1e46af8ac0c1b01c8e63feec0930b6a2b2568d0f49fef6ab053455be8837e01e46ef36b6ea6067d19820239bf)
5667 verbose stack     at Readable.body.on.err (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:195:14)
5667 verbose stack     at emitOne (events.js:116:13)
5667 verbose stack     at Readable.emit (events.js:211:7)
5667 verbose stack     at cacache.get.byDigest.then.err (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\cache.js:92:30)
5667 verbose stack     at tryCatcher (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
5667 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
5667 verbose stack     at Promise._settlePromise (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
5667 verbose stack     at Promise._settlePromise0 (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
5667 verbose stack     at Promise._settlePromises (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:695:18)
5667 verbose stack     at _drainQueueStep (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
5667 verbose stack     at _drainQueue (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
5667 verbose stack     at Async._drainQueues (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
5667 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\V002322\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
5667 verbose stack     at runCallback (timers.js:810:20)
5667 verbose stack     at tryOnImmediate (timers.js:768:5)
5667 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by zayn-m** [comment]
> Hi @Zayn484 👋 Can you post the full error log? I'm not actively working on this project anymore but can help you get it running locally!

These are the errors i get while npm install, please help!

C:\Users\Pc 1\Dev\shirts\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Pc 1\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Pc 1\Dev\shirts\node_modules\canvas
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

C:\Users\Pc 1\Dev\shirts\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Pc 1\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Pc 1\Dev\shirts\node_modules\contextify
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.2 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngrok@2.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pc 1\AppData\Roaming\npm-cache\_logs\2019-07-30T05_36_50_310Z-debug.log

**Comment by muhammadAhmedatherUsmani** [comment]
ahmed@Ahmed:~/Documents/Projects-CBP/shirts$ sudo npm start

> react-boilerplate@3.2.0 start /home/ahmed/Documents/Projects-CBP/shirts
> cross-env NODE_ENV=development node server

module.js:549
    throw err;
    ^

Error: Cannot find module './s3config.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ahmed/Documents/Projects-CBP/shirts/server/api.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.15.0-58-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.2.0 start script 'cross-env NODE_ENV=development node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ahmed/Documents/Projects-CBP/shirts/npm-debug.log

**Comment by JayeshSomala** [comment]
hi @paulxuca , great project 
can you kindly tell me the steps to run the project .
I installed the dependencies and ran yarn start I am getting a pages as follows.
<img width="952" alt="Screenshot 2022-09-21 104215" src="https://user-images.githubusercontent.com/81252822/191419545-82e1de8a-4668-40b3-ac24-db476ca0f50c.png">
can you kindly tell me the further steps to be followed .
I even added s3.config file inside server folder.

**Comment by muhammadAhmedatherUsmani** [comment]
Yes please contact me on whats app 
00923323086701

**Comment by alliancenshuti** [comment]
> hi @paulxuca , great project can you kindly tell me the steps to run the project . I installed the dependencies and ran yarn start I am getting a pages as follows. <img alt="Screenshot 2022-09-21 104215" width="952" src="https://user-images.githubusercontent.com/81252822/191419545-82e1de8a-4668-40b3-ac24-db476ca0f50c.png"> can you kindly tell me the further steps to be followed . I even added s3.config file inside server folder.

am also trying to run the project if, by any chance you figured out how to do it, I would appreciate it if you share it with me. thanks
